# Generated by Django 4.2.2 on 2023-06-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_opinion_comment_alter_opinion_personnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='comment',
        ),
    ]
