# Generated by Django 4.2.2 on 2023-06-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_movie_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='comment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.comment'),
            preserve_default=False,
        ),
    ]
