# Generated by Django 4.2.2 on 2023-06-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_comment_content_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='movie_choice',
            field=models.CharField(choices=[('Select Movie', 'Select Movie'), (1, 'Toy Story')], default=('Select Movie', 'Select Movie')),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='content',
            field=models.CharField(max_length=10000, verbose_name='explanation'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='tldr',
            field=models.CharField(max_length=150, verbose_name='opinion'),
        ),
    ]
