# Generated by Django 4.2.2 on 2023-06-22 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_merge_20230621_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='movie_choice',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='person',
            field=models.ForeignKey(db_column='cast or crew member', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.personnel'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='person_role',
            field=models.CharField(choices=[('Actor', 'Actor'), ('Director', 'Director'), ('Writer', 'Writer'), ('Producer', 'Producer'), ('Casting Director', 'Casting Director'), ('Cinematographer', 'Cinematographer'), ('Score', 'Score')], default=('Actor', 'Actor'), null=True, verbose_name='role'),
        ),
    ]
