# Generated by Django 4.2.2 on 2023-06-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_opinion_check_person_opinion_person_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='check_person',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='movie_choice',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='role',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='person',
            field=models.ForeignKey(db_column='cast or crew member', null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.personnel'),
        ),
    ]
