# Generated by Django 4.2.2 on 2023-06-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_opinion_check_person_opinion_person_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='check_person',
        ),
    ]
