<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-06-20 18:45
=======
# Generated by Django 4.2.2 on 2023-06-20 18:38
>>>>>>> ae61ad2a30b7c3ff3bb7759e7803f4f2977c9f66

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_opinion_movie_choice_alter_opinion_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='movie_choice',
<<<<<<< HEAD
            field=models.CharField(choices=[('Select Movie', 'Select Movie'), (1, 'Star Trek Wrath of Khan')], default=('Select Movie', 'Select Movie')),
=======
            field=models.CharField(choices=[('Select Movie', 'Select Movie'), (2, 'It'), (1, 'Interstellar'), (9, 'Minority Report'), (10, 'Arrival'), (12, 'Tron'), (13, 'Tron: Legacy')], default=('Select Movie', 'Select Movie')),
>>>>>>> ae61ad2a30b7c3ff3bb7759e7803f4f2977c9f66
        ),
    ]