# Generated by Django 4.2.2 on 2023-06-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_opinion_movie_choice_delete_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('movie_choice', models.CharField(max_length=150, verbose_name='movie')),
                ('movies', models.ManyToManyField(to='main_app.movie')),
            ],
        ),
    ]