# Generated by Django 4.2.2 on 2023-06-21 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.personnel'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='person_role',
            field=models.CharField(choices=[('Actor', 'Actor'), ('Director', 'Director'), ('Writer', 'Writer'), ('Producer', 'Producer'), ('Casting Director', 'Casting Director'), ('Cinematographer', 'Cinematographer'), ('Score', 'Score')], default=('Actor', 'Actor'), verbose_name='role'),
        ),
    ]