# Generated by Django 4.2.2 on 2023-06-21 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_opinion_movie_choice'),
        ('main_app', '0008_opinion_person_opinion_person_role'),
    ]

    operations = [
    ]