# Generated by Django 4.2.2 on 2023-06-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_merge_20230621_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='movie_choice',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='role',
        ),
        migrations.AlterField(
            model_name='opinion',
            name='movie_choice',
            field=models.CharField(max_length=150, verbose_name='movie'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='person_role',
            field=models.CharField(choices=[('Actor', 'Actor'), ('Director', 'Director'), ('Writer', 'Writer'), ('Producer', 'Producer'), ('Casting Director', 'Casting Director'), ('Cinematographer', 'Cinematographer'), ('Score', 'Score')], default=('Actor', 'Actor'), null=True, verbose_name='role'),
        ),
    ]